### ISSUE TITLE
Support non-linear ranges

### ISSUE THREAD

**Issue by etimberg** [react-tools/react-ranger#3]
Got this idea when playing with the `custom-steps` sample. Would be cool to support a logarithmic interpolation on the slider.

## Implementation Ideas

1. Built in support for `'linear'` and `'logarithmic'` interpolation
2. Custom interpolation support via props

**Comment by tannerlinsley** [comment]
The scale used internally could easily be exposed. All it does is translate a value into a width percentage. :)

**Comment by etimberg** [comment]
Already working on it ;)

**Comment by tannerlinsley** [comment]
Nice!

**Comment by etimberg** [comment]
Done in #5
